src/Entity/CarnetSante.php
<?php

namespace App\Entity;

use App\Repository\CarnetSanteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarnetSanteRepository::class)]
class CarnetSante
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $vaccins = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_vaccination = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_future_vaccination = null;

    #[ORM\OneToOne(inversedBy: 'carnetSante', cascade: ['persist', 'remove'])]

    #[ORM\JoinColumn(nullable: false)]
    private ?Animal $animal = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVaccins(): ?string
    {
        return $this->vaccins;
    }

    public function setVaccins(string $vaccins): static
    {
        $this->vaccins = $vaccins;

        return $this;
    }

    public function getDateVaccination(): ?\DateTime
    {
        return $this->date_vaccination;
    }

    public function setDateVaccination(\DateTime $date_vaccination): static
    {
        $this->date_vaccination = $date_vaccination;

        return $this;
    }

    public function getDateFutureVaccination(): ?\DateTime
    {
        return $this->date_future_vaccination;
    }

    public function setDateFutureVaccination(\DateTime $date_future_vaccination): static
    {
        $this->date_future_vaccination = $date_future_vaccination;

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function setAnimal(?Animal $animal): static
    {
        $this->animal = $animal;
        return $this;
    }
}

src/Form/CarnetSanteType.php
<?php

namespace App\Form;

use App\Entity\Animal;
use App\Entity\CarnetSante;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarnetSanteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('vaccins')
            ->add('date_vaccination')
            ->add('date_future_vaccination')
            ->add('animal', EntityType::class, [
                'class' => Animal::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CarnetSante::class,
        ]);
    }
}

src/Controller/CarnetSanteController.php
<?php

namespace App\Controller;

use App\Entity\CarnetSante;
use App\Form\CarnetSanteType;
use App\Repository\CarnetSanteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/carnet/sante')]
final class CarnetSanteController extends AbstractController
{
    #[Route(name: 'app_carnet_sante_index', methods: ['GET'])]
    public function index(CarnetSanteRepository $carnetSanteRepository): Response
    {
        return $this->render('carnet_sante/index.html.twig', [
            'carnet_santes' => $carnetSanteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_carnet_sante_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $carnetSante = new CarnetSante();
        $form = $this->createForm(CarnetSanteType::class, $carnetSante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($carnetSante);
            $entityManager->flush();

            return $this->redirectToRoute('app_carnet_sante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('carnet_sante/new.html.twig', [
            'carnet_sante' => $carnetSante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_carnet_sante_show', methods: ['GET'])]
    public function show(CarnetSante $carnetSante): Response
    {
        return $this->render('carnet_sante/show.html.twig', [
            'carnet_sante' => $carnetSante,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_carnet_sante_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CarnetSante $carnetSante, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CarnetSanteType::class, $carnetSante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_carnet_sante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('carnet_sante/edit.html.twig', [
            'carnet_sante' => $carnetSante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_carnet_sante_delete', methods: ['POST'])]
    public function delete(Request $request, CarnetSante $carnetSante, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$carnetSante->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($carnetSante);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_carnet_sante_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/carnet_sante/_delete_form.html.twig
<form method="post" action="{{ path('app_carnet_sante_delete', {'id': carnet_sante.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carnet_sante.id) }}">
    <button class="btn">Delete</button>
</form>

templates/carnet_sante/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/carnet_sante/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CarnetSante{% endblock %}

{% block body %}
    <h1>Edit CarnetSante</h1>

    {{ include('carnet_sante/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_carnet_sante_index') }}">back to list</a>

    {{ include('carnet_sante/_delete_form.html.twig') }}
{% endblock %}

templates/carnet_sante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarnetSante index{% endblock %}

{% block body %}
    <h1>CarnetSante index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Vaccins</th>
                <th>Date_vaccination</th>
                <th>Date_future_vaccination</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for carnet_sante in carnet_santes %}
            <tr>
                <td>{{ carnet_sante.id }}</td>
                <td>{{ carnet_sante.vaccins }}</td>
                <td>{{ carnet_sante.dateVaccination ? carnet_sante.dateVaccination|date('Y-m-d') : '' }}</td>
                <td>{{ carnet_sante.dateFutureVaccination ? carnet_sante.dateFutureVaccination|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_carnet_sante_show', {'id': carnet_sante.id}) }}">show</a>
                    <a href="{{ path('app_carnet_sante_edit', {'id': carnet_sante.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_carnet_sante_new') }}">Create new</a>
{% endblock %}

templates/carnet_sante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CarnetSante{% endblock %}

{% block body %}
    <h1>Create new CarnetSante</h1>

    {{ include('carnet_sante/_form.html.twig') }}

    <a href="{{ path('app_carnet_sante_index') }}">back to list</a>
{% endblock %}

templates/carnet_sante/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarnetSante{% endblock %}

{% block body %}
    <h1>CarnetSante</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ carnet_sante.id }}</td>
            </tr>
            <tr>
                <th>Vaccins</th>
                <td>{{ carnet_sante.vaccins }}</td>
            </tr>
            <tr>
                <th>Date_vaccination</th>
                <td>{{ carnet_sante.dateVaccination ? carnet_sante.dateVaccination|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_future_vaccination</th>
                <td>{{ carnet_sante.dateFutureVaccination ? carnet_sante.dateFutureVaccination|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_carnet_sante_index') }}">back to list</a>

    <a href="{{ path('app_carnet_sante_edit', {'id': carnet_sante.id}) }}">edit</a>

    {{ include('carnet_sante/_delete_form.html.twig') }}
{% endblock %}