src/Entity/Ordre.php
<?php

namespace App\Entity;

use App\Repository\OrdreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdreRepository::class)]
class Ordre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom_ordre = null;

    /**
     * @var Collection<int, Famille>
     */
    #[ORM\OneToMany(targetEntity: Famille::class, mappedBy: 'ordre')]
    private Collection $familles;

    public function __construct()
    {
        $this->familles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomOrdre(): ?string
    {
        return $this->nom_ordre;
    }

    public function setNomOrdre(string $nom_ordre): static
    {
        $this->nom_ordre = $nom_ordre;

        return $this;
    }

    /**
     * @return Collection<int, Famille>
     */
    public function getFamilles(): Collection
    {
        return $this->familles;
    }

    public function addFamille(Famille $famille): static
    {
        if (!$this->familles->contains($famille)) {
            $this->familles->add($famille);
            $famille->setOrdre($this);
        }

        return $this;
    }

    public function removeFamille(Famille $famille): static
    {
        if ($this->familles->removeElement($famille)) {
            // set the owning side to null (unless already changed)
            if ($famille->getOrdre() === $this) {
                $famille->setOrdre(null);
            }
        }

        return $this;
    }
}

src/Form/OrdreType.php
<?php

namespace App\Form;

use App\Entity\Ordre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrdreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_ordre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ordre::class,
        ]);
    }
}

src/Controller/OrdreController.php
<?php

namespace App\Controller;

use App\Entity\Ordre;
use App\Form\OrdreType;
use App\Repository\OrdreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/ordre')]
final class OrdreController extends AbstractController
{
    #[Route(name: 'app_ordre_index', methods: ['GET'])]
    public function index(OrdreRepository $ordreRepository): Response
    {
        return $this->render('ordre/index.html.twig', [
            'ordres' => $ordreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_ordre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $ordre = new Ordre();
        $form = $this->createForm(OrdreType::class, $ordre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($ordre);
            $entityManager->flush();

            return $this->redirectToRoute('app_ordre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ordre/new.html.twig', [
            'ordre' => $ordre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ordre_show', methods: ['GET'])]
    public function show(Ordre $ordre): Response
    {
        return $this->render('ordre/show.html.twig', [
            'ordre' => $ordre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ordre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ordre $ordre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OrdreType::class, $ordre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_ordre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ordre/edit.html.twig', [
            'ordre' => $ordre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ordre_delete', methods: ['POST'])]
    public function delete(Request $request, Ordre $ordre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ordre->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($ordre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_ordre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ordre/_delete_form.html.twig
<form method="post" action="{{ path('app_ordre_delete', {'id': ordre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ordre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ordre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ordre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ordre{% endblock %}

{% block body %}
    <h1>Edit Ordre</h1>

    {{ include('ordre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_ordre_index') }}">back to list</a>

    {{ include('ordre/_delete_form.html.twig') }}
{% endblock %}

templates/ordre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ordre index{% endblock %}

{% block body %}
    <h1>Ordre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_ordre</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ordre in ordres %}
            <tr>
                <td>{{ ordre.id }}</td>
                <td>{{ ordre.nomOrdre }}</td>
                <td>
                    <a href="{{ path('app_ordre_show', {'id': ordre.id}) }}">show</a>
                    <a href="{{ path('app_ordre_edit', {'id': ordre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_ordre_new') }}">Create new</a>
{% endblock %}

templates/ordre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ordre{% endblock %}

{% block body %}
    <h1>Create new Ordre</h1>

    {{ include('ordre/_form.html.twig') }}

    <a href="{{ path('app_ordre_index') }}">back to list</a>
{% endblock %}

templates/ordre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ordre{% endblock %}

{% block body %}
    <h1>Ordre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ordre.id }}</td>
            </tr>
            <tr>
                <th>Nom_ordre</th>
                <td>{{ ordre.nomOrdre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_ordre_index') }}">back to list</a>

    <a href="{{ path('app_ordre_edit', {'id': ordre.id}) }}">edit</a>

    {{ include('ordre/_delete_form.html.twig') }}
{% endblock %}