src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Enum\Sexe;
use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnimalRepository::class)]
class Animal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 10)]
    private ?string $num_identification = null;

    #[ORM\Column(enumType: Sexe::class)]
    private ?Sexe $sexe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_arrivee = null;

    #[ORM\Column]
    private ?bool $est_adoptable = null;

    /**
     * @var Collection<int, Maladie>
     */
    #[ORM\ManyToMany(targetEntity: Maladie::class, mappedBy: 'animal')]
    private Collection $maladies;

    #[ORM\OneToOne(mappedBy: 'animal', cascade: ['persist', 'remove'])]
    private ?CarnetSante $carnetSante = null;

    #[ORM\ManyToOne(inversedBy: 'animal')]
    private ?Menu $menu = null;

    #[ORM\ManyToOne(inversedBy: 'animal')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cage $cage = null;

    #[ORM\ManyToOne(inversedBy: 'animal')]
    private ?Adoptant $adoptant = null;

    public function __construct()
    {
        $this->maladies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTime
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTime $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getNumIdentification(): ?string
    {
        return $this->num_identification;
    }

    public function setNumIdentification(string $num_identification): static
    {
        $this->num_identification = $num_identification;

        return $this;
    }

    public function getSexe(): ?Sexe
    {
        return $this->sexe;
    }

    public function setSexe(Sexe $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateArrivee(): ?\DateTime
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTime $date_arrivee): static
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function isEstAdoptable(): ?bool
    {
        return $this->est_adoptable;
    }

    public function setEstAdoptable(bool $est_adoptable): static
    {
        $this->est_adoptable = $est_adoptable;

        return $this;
    }

    /**
     * @return Collection<int, Maladie>
     */
    public function getMaladies(): Collection
    {
        return $this->maladies;
    }

    public function addMalady(Maladie $malady): static
    {
        if (!$this->maladies->contains($malady)) {
            $this->maladies->add($malady);
            $malady->addAnimal($this);
        }

        return $this;
    }

    public function removeMalady(Maladie $malady): static
    {
        if ($this->maladies->removeElement($malady)) {
            $this->$malady->removeAnimal($this);
        }
        return $this;
    }

    public function getCarnetSante(): ?CarnetSante
    {
        return $this->carnetSante;
    }

    public function setCarnetSante(CarnetSante $carnetSante): static
    {
        // set the owning side of the relation if necessary
        if ($carnetSante->getAnimal() !== $this) {
            $carnetSante->setAnimal($this);
        }

        $this->carnetSante = $carnetSante;

        return $this;
    }

    public function getMenu(): ?Menu
    {
        return $this->menu;
    }

    public function setMenu(?Menu $menu): static
    {
        $this->menu = $menu;

        return $this;
    }

    public function getCage(): ?Cage
    {
        return $this->cage;
    }

    public function setCage(?Cage $cage): static
    {
        $this->cage = $cage;

        return $this;
    }

    public function getAdoptant(): ?Adoptant
    {
        return $this->adoptant;
    }

    public function setAdoptant(?Adoptant $adoptant): static
    {
        $this->adoptant = $adoptant;

        return $this;
    }
}

src/Form/AnimalType.php
<?php

namespace App\Form;

use App\Entity\Animal;
use App\Entity\Cage;
use App\Entity\CarnetSante;
use App\Entity\Maladie;
use App\Entity\Menu;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnimalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_naissance')
            ->add('description')
            ->add('num_identification')
            ->add('sexe')
            ->add('date_arrivee')
            ->add('est_adoptable')
            ->add('maladies', EntityType::class, [
                'class' => Maladie::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('carnetSante', EntityType::class, [
                'class' => CarnetSante::class,
                'choice_label' => 'id',
            ])
            ->add('menu', EntityType::class, [
                'class' => Menu::class,
                'choice_label' => 'id',
            ])
            ->add('cage', EntityType::class, [
                'class' => Cage::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Animal::class,
        ]);
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/animal')]
final class AnimalController extends AbstractController
{
    #[Route(name: 'app_animal_index', methods: ['GET'])]
    public function index(AnimalRepository $animalRepository): Response
    {
        return $this->render('animal/index.html.twig', [
            'animals' => $animalRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_animal_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($animal);
            $entityManager->flush();

            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('animal/new.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_animal_show', methods: ['GET'])]
    public function show(Animal $animal): Response
    {
        return $this->render('animal/show.html.twig', [
            'animal' => $animal,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_animal_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Animal $animal, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('animal/edit.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_animal_delete', methods: ['POST'])]
    public function delete(Request $request, Animal $animal, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$animal->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($animal);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/animal/_delete_form.html.twig
<form method="post" action="{{ path('app_animal_delete', {'id': animal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ animal.id) }}">
    <button class="btn">Delete</button>
</form>

templates/animal/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/animal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Animal{% endblock %}

{% block body %}
    <h1>Edit Animal</h1>

    {{ include('animal/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_animal_index') }}">back to list</a>

    {{ include('animal/_delete_form.html.twig') }}
{% endblock %}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal index
{% endblock %}

{% block body %}
	<h1>Animal index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nom</th>
				<th>Date_naissance</th>
				<th>Description</th>
				<th>Num_identification</th>
				<th>Sexe</th>
				<th>Date_arrivee</th>
				<th>Est_adoptable</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for animal in animals %}
				<tr>
					<td>{{ animal.id }}</td>
					<td>{{ animal.nom }}</td>
					<td>{{ animal.dateNaissance ? animal.dateNaissance|date('Y-m-d') : '' }}</td>
					<td>{{ animal.description }}</td>
					<td>{{ animal.numIdentification }}</td>
					<td>{{ animal.sexe.label() }}</td>
					<td>{{ animal.dateArrivee ? animal.dateArrivee|date('Y-m-d') : '' }}</td>
					<td>{{ animal.estAdoptable ? 'Yes' : 'No' }}</td>
					<td>
						<a href="{{ path('app_animal_show', {'id': animal.id}) }}">show</a>
						<a href="{{ path('app_animal_edit', {'id': animal.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="9">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_animal_new') }}">Create new</a>
{% endblock %}

templates/animal/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Animal{% endblock %}

{% block body %}
    <h1>Create new Animal</h1>

    {{ include('animal/_form.html.twig') }}

    <a href="{{ path('app_animal_index') }}">back to list</a>
{% endblock %}

templates/animal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
    <h1>Animal</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ animal.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ animal.nom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ animal.dateNaissance ? animal.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ animal.description }}</td>
            </tr>
            <tr>
                <th>Num_identification</th>
                <td>{{ animal.numIdentification }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ animal.sexe }}</td>
            </tr>
            <tr>
                <th>Date_arrivee</th>
                <td>{{ animal.dateArrivee ? animal.dateArrivee|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Est_adoptable</th>
                <td>{{ animal.estAdoptable ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_animal_index') }}">back to list</a>

    <a href="{{ path('app_animal_edit', {'id': animal.id}) }}">edit</a>

    {{ include('animal/_delete_form.html.twig') }}
{% endblock %}