src/Entity/Maladie.php
<?php

namespace App\Entity;

use App\Repository\MaladieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaladieRepository::class)]
class Maladie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom_maladie = null;
    /**
     * @var Collection<int, Animal>
     */
    #[ORM\ManyToMany(targetEntity: Animal::class, inversedBy: 'maladies')]
    private Collection $animal;

    public function __construct()
    {
        $this->animal = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomMaladie(): ?string
    {
        return $this->nom_maladie;
    }

    public function setNomMaladie(string $nom_maladie): static
    {
        $this->nom_maladie = $nom_maladie;

        return $this;
    }


    /**
     * @return Collection<int, Animal>
     */
    public function getAnimal(): Collection
    {
        return $this->animal;
    }


    public function setAnimal(?Animal $animal): static
    {
        $this->animal = $animal;
    }
    public function addAnimal(Animal $animal): static
    {
        if (!$this->animal->contains($animal)) {
            $this->animal->add($animal);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): static
    {
        $this->animal->removeElement($animal);
        return $this;
    }
}

src/Form/MaladieType.php
<?php

namespace App\Form;

use App\Entity\Animal;
use App\Entity\Maladie;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaladieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_maladie')
            ->add('animal', EntityType::class, [
                'class' => Animal::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Maladie::class,
        ]);
    }
}

src/Controller/MaladieController.php
<?php

namespace App\Controller;

use App\Entity\Maladie;
use App\Form\MaladieType;
use App\Repository\MaladieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/maladie')]
final class MaladieController extends AbstractController
{
    #[Route(name: 'app_maladie_index', methods: ['GET'])]
    public function index(MaladieRepository $maladieRepository): Response
    {
        return $this->render('maladie/index.html.twig', [
            'maladies' => $maladieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_maladie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $maladie = new Maladie();
        $form = $this->createForm(MaladieType::class, $maladie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($maladie);
            $entityManager->flush();

            return $this->redirectToRoute('app_maladie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('maladie/new.html.twig', [
            'maladie' => $maladie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_maladie_show', methods: ['GET'])]
    public function show(Maladie $maladie): Response
    {
        return $this->render('maladie/show.html.twig', [
            'maladie' => $maladie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_maladie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Maladie $maladie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MaladieType::class, $maladie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_maladie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('maladie/edit.html.twig', [
            'maladie' => $maladie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_maladie_delete', methods: ['POST'])]
    public function delete(Request $request, Maladie $maladie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$maladie->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($maladie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_maladie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/maladie/_delete_form.html.twig
<form method="post" action="{{ path('app_maladie_delete', {'id': maladie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ maladie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/maladie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/maladie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Maladie{% endblock %}

{% block body %}
    <h1>Edit Maladie</h1>

    {{ include('maladie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_maladie_index') }}">back to list</a>

    {{ include('maladie/_delete_form.html.twig') }}
{% endblock %}

templates/maladie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Maladie index{% endblock %}

{% block body %}
    <h1>Maladie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_maladie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for maladie in maladies %}
            <tr>
                <td>{{ maladie.id }}</td>
                <td>{{ maladie.nomMaladie }}</td>
                <td>
                    <a href="{{ path('app_maladie_show', {'id': maladie.id}) }}">show</a>
                    <a href="{{ path('app_maladie_edit', {'id': maladie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_maladie_new') }}">Create new</a>
{% endblock %}

templates/maladie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Maladie{% endblock %}

{% block body %}
    <h1>Create new Maladie</h1>

    {{ include('maladie/_form.html.twig') }}

    <a href="{{ path('app_maladie_index') }}">back to list</a>
{% endblock %}

templates/maladie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Maladie{% endblock %}

{% block body %}
    <h1>Maladie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ maladie.id }}</td>
            </tr>
            <tr>
                <th>Nom_maladie</th>
                <td>{{ maladie.nomMaladie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_maladie_index') }}">back to list</a>

    <a href="{{ path('app_maladie_edit', {'id': maladie.id}) }}">edit</a>

    {{ include('maladie/_delete_form.html.twig') }}
{% endblock %}